### ISSUE TITLE
Panic on server shutdown

### ISSUE THREAD

**Issue by mpldr** [valyala/fasthttp#1504]
I encounter [this panic](https://github.com/valyala/fasthttp/blob/v1.44.0/peripconn.go#L35) when shutting down the server.

The steps are:
- start server
- get index page with firefox
- send sigint (invalidates the context)
- see panic

Server setup/shutdown:
```go
	lis, err := net.Listen("tcp", "localhost:8080")
	if err != nil {
		glog.Errorf("failed to listen on %s: %v", ":8080", err)
		return
	}
	srv := &fasthttp.Server{
		Handler:                      handler.RootHandler,
		MaxConnsPerIP:                1,
		MaxRequestBodySize:           260 * 1024 * 1024,
		DisablePreParseMultipartForm: true,
		StreamRequestBody:            true,
		TLSConfig:                    &tls.Config{},
	}
	httpErr := make(chan error)
	go func() {
		httpErr <- srv.Serve(lis)
	}()

	select {
	case err = <-httpErr:
		if err != nil {
			glog.Errorf("server encoutered an error. not good: %v", err) // TODO: might want to rephrase this
		}
		errchan <- err
		fmt.Println(err)
	case <-ctx.Done():
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		srv.ShutdownWithContext(ctx)
		cancel()
		return
	}

```

**Comment by mpldr** [comment]
Not sure if the first even has to be a panic, to be honest. Looks like nothing but a sanity check to me.

**Comment by li-jin-gou** [comment]
hello @mpldr  Can you provide a complete runnable code ? I would like to try to reproduce this problem in my computer.

**Comment by mpldr** [comment]
Sure, here you go: http://0x0.st/Hs5T.tzst

It's not yet part of any repo, so a tarball is the best I can offer you right away :)

**Comment by erikdubbelboer** [comment]
The problem is that `Shutdown` calls `closeIdleConns`. Which calls `Close` on all connections here: https://github.com/valyala/fasthttp/blob/559d536fd42f8d6099fa88bf788e2cc7dbb65d83/server.go#L2903
But then when the worker goroutine stops it also calls `Close` on the connection here: https://github.com/valyala/fasthttp/blob/404c8a896896943715f8fb3906a8d054fae17d3e/workerpool.go#L238

We should somehow stop one of them from happening. I think `closeIdleConns` needs to call `Close` to stop the read in `serveConn`. So we'll need some way for `workerFunc` not to close the connection. I'm not sure in which case this close is needed.

I'm afraid I don't have time to investigate this further right now. I'll have another look in the future.

**Comment by mpldr** [comment]
Thinking of it, I more and more think this shouldn't be a panic but instead handled gracefully™ (which might mean discarding after logging in this case)

**Comment by erikdubbelboer** [comment]
Should be fixed in https://github.com/valyala/fasthttp/pull/1526

**Comment by mpldr** [comment]
As mentioned in #1526 it now doesn't panic anymore. The underlying double close is not fixed. So not sure if this ticket should be renamed.
